FROM python:3.13-slim-bookworm
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY apps/satellite/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY apps/satellite/satellite.py ./
COPY apps/satellite/tests ./tests
ENTRYPOINT ["python", "/app/satellite.py"]
CMD ["--help"]
